### Enums ###
enum TutorTypes {
    WRITING
    CONTENT
}
enum RequestStatus {
    PENDING
    ASSIGNED
    COMPLETED
    # Archived?
}
###############

### Collections ###
type Session @collection(name: "Sessions") {
    user: Student
}

type Student @collection(name: "Students") {
    username: String
    passwordHash: String

    name: String
    classStanding: Int
    majors: [String]
    minors: [String]
    tutorTypes: [TutorTypes]
    courses: [Course] @relation(name: "student_courses")

    requests: [Request] @relation(name: "student_requests")
    assignments: [Request] @relation(name: "student_assignments")
}

type Course @collection(name: "Courses") {
    title: String
    subject: String
    level: Int
    professor: String
    students: [Student] @relation(name: "student_courses")
}

type Request @collection(name: "Requests") {
    tutor: Student @relation(name: "student_assignments")
    tutee: Student @relation(name: "student_requests")
    status: RequestStatus

    course: Course
    descripIfNotCourse: String
    tutorType: String
    description: String
}
###############

### Queries ###
type Query {
    allStudents: [Student]
    allCourses: [Course]
    allRequests: [Request]

    getStudentByUsername(username: String): Student
}
###############
